# Generated by Django 4.2.11 on 2025-12-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("client_phone", models.CharField(blank=True, max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "is_finalized",
                    models.BooleanField(
                        default=False,
                        help_text="If True, stock is deducted and revenue is booked.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price sold to client",
                        max_digits=10,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order.salesorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FreelanceJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("STEEL", "Steel Work"),
                            ("ELECTRIC", "Electrician"),
                            ("INSTALL", "General Installation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "contractor_name",
                    models.CharField(
                        help_text="Who is doing the work?", max_length=200
                    ),
                ),
                (
                    "cost_to_company",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="What we pay the contractor",
                        max_digits=10,
                    ),
                ),
                (
                    "charge_to_client",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="What we bill the client",
                        max_digits=10,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelance_jobs",
                        to="order.salesorder",
                    ),
                ),
            ],
        ),
    ]
