# Generated by Django 4.2.11 on 2025-12-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, help_text="Average cost to buy", max_digits=10
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Standard selling price",
                        max_digits=10,
                    ),
                ),
                ("current_stock", models.IntegerField(default=0)),
                (
                    "reorder_threshold",
                    models.IntegerField(
                        default=10, help_text="Alert when stock drops below this"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.category",
                    ),
                ),
            ],
        ),
    ]
