# Generated by Django 4.2.11 on 2025-12-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyFinancialRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_cogs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Cost of Goods Sold",
                        max_digits=12,
                    ),
                ),
                (
                    "total_freelance_costs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Paid to contractors",
                        max_digits=12,
                    ),
                ),
                (
                    "total_operational_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Rent, Marketing, etc.",
                        max_digits=12,
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RENT", "Rent"),
                            ("SALARY", "Salaries"),
                            ("MARKETING", "Marketing"),
                            ("UTILITIES", "Utilities"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                (
                    "receipt_image",
                    models.ImageField(blank=True, null=True, upload_to="expenses/"),
                ),
            ],
        ),
    ]
